server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5436/practice_feign
    username: leanghuy
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
springdoc:
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: false